### ISSUE TITLE
Error uploading to Rackspace

### ISSUE THREAD

**Issue by tomfrew** [keystonejs/storage#10]
When only uploading to Rackspace, upload fail with the following error:

```
/Users/***/storagejs/provider/amazon.js:85
    this._connection.createContainer(this._config.container, function (err) {
                     ^
TypeError: Cannot call method 'createContainer' of undefined
    at RackspaceClient.AmazonClient._init (/Users/Tom/Documents/Development/watch/storagejs/provider/amazon.js:85:19)
    at Object.Storage.get (/Users/Tom/Documents/Development/watch/storagejs/index.js:102:10)
    at gm.<anonymous> (/Users/Tom/Documents/Development/watch/app.js:41:15)
    at cb (/Users/Tom/Documents/Development/watch/gm/lib/command.js:270:16)
    at ChildProcess._spawn.proc.on.onExit (/Users/Tom/Documents/Development/watch/gm/lib/command.js:252:9)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**Comment by grabbou** [comment]
Thanks @tomfrew for your bug report. Going to fix that pretty soon along with other repo changes I've done and that are waiting to be committed.
